# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Sammy Shaw
description: "Hi, I’m Sammy – Data Scientist and Researcher.
My portfolio is a collection of recent data science projects - emphasis on data processing and analysis, machine learning, business problem solving, and programming. My statistics and research expertise comes from my PhD in Sociology, which also equips me with a unique perspective on social trends and patterns, crucial for interpreting social dynamics with data that are invaluable for predicting consumer behavior, identifying market trends, and addressing issues of equity and inclusion.  

Check out my Linked In profile, Github, and download my resume below!

"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Seattle, WA"
resume_url: /docs/ShawResume_TEMP_DEC2025.pdf
avatar_image: img/mug%20shot.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/samuel-shaw-sammy-shaw/" # Add your linkedln handle
github: "https://github.com/SammyShaw/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


