# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Sammy Shaw
description: "Hi, I’m Sammy – Data Scientist and Researcher.
My porfolio is a collection of recent data-driven projects and demos, emphasis on data analysis, visualization, basic programming, and data problem-solving. I have a PhD in Sociology, so I love to derive insights about human behavior from large public data sets like the General Social Survey and the American Community Survey.

Feel free to explore my GitHub for project details, check out my LinkedIn, or download my resume below!

"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Seattle, WA"
resume_url: docs/SamuelShawResume_Sept2024.docx
avatar_image: img/mug%20shot.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/samuel-shaw77/" # Add your linkedln handle
github: "https://github.com/SammyShaw/SammyShaw"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

