# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Sammy Shaw
description: "Hi, I’m Sammy – Data Scientist and Researcher.
This portfolio contains a set of independently developed data science projects demonstrating my approach to analytical problem solving. Each project includes end-to-end data work — ingestion, cleaning, feature engineering, modeling, evaluation, and interpretation.

My training as a sociologist deepens this work by grounding analysis in context and behavior: understanding not just what patterns exist, but why they matter. I am especially interested in roles where data science, human behavior, and practical decision making intersect.

Check out my Linked In profile, Github, and download my resume below!

"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Seattle, WA"
resume_url: /docs/ShawResume_TEMP_DEC2025.pdf
avatar_image: img/mug%20shot.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/samuel-shaw-sammy-shaw/" # Add your linkedln handle
github: "https://github.com/SammyShaw/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



